name: build java_zulu

on:
  workflow_dispatch:
  schedule:
    - cron: "0 17 1,15 * *" # bi-weekly on 1st and 15th calendar day at 17:00
  push:
    branches:
      - main
    paths:
      - nosql/mongodb/**

permissions:
  actions: read
  packages: write

concurrency:
  group: mongodb-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  push:
    name: "pterodactyl-images:mongodb_${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - 8
    steps:
      - name: Git checkout for Github repository workspace
        uses: actions/checkout@v4

      - name: Setup QEMU for multiarch builds
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.SECRET_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: ./nosql/mongodb
          platforms: linux/amd64, linux/arm64
          file: ./nosql/mongodb/${{ matrix.tag }}/Dockerfile
          push: true
          tags: ghcr.io/worldmandia/pterodactyl-images:mongodb_${{ matrix.tag }}
